#!/bin/bash	

function set_prompt () {
    brd="\[\033["$1"m\]"
    fld="\[\033["$2"m\]"
    hst="\[\033["$3"m\]"
    cmd="\[\033[0;37m\]"
    

    PS1="$brd{$fld\!$brd}-{$fld\t$brd}-{$fld\w$brd}$fld\n"
    export PS1=$PS1"$brd{$fld\u@$hst\h$brd}$cmd\$ "
}

function prompt_template () {
    case $1 in
        jorge)
            colors=("0;33" "0;32" "1;32")
        ;;
        root)
            colors=("0;33" "0;31" "1;31")
        ;;
        blue)
            colors=("1;34" "0;34" "0;36")
        ;;
        purple)
            colors=("1;35" "0;35" "1;30")
        ;;
        sherbet)
            colors=("1;35" "0;34" "1;34")
        ;;
        test)
            colors=("1;35" "0;34" "1;34")
        ;;
    esac
    set_prompt ${colors[0]} ${colors[1]} ${colors[2]}
}

